# Generated by Django 5.1.3 on 2024-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("timeslot", models.SmallIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
